name: Edward Hotchkiss - Software Engineer
description: I'm a Software Engineer and Entrepreneur based in NYC
url: http://edwardhotchkiss.com/
auto: true
pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
rdiscount:
  extensions: [smart]
