source: .
destination: ./_site
includes: ./_includes
plugins: ./_plugins
base_url: /
name: Edward Hotchkiss - Software Engineer
description: I'm a Software Engineer and Entrepreneur based in NYC
url: http://edwardhotchkiss.com/
leftCurleys: "{{"
rightCurleys: "}}"
auto: true
pygments: true
markdown: rdiscount
permalink: /blog/:year/:month/:day/:title
rdiscount:
  extensions: [smart]

exclude: ['application.rb', 'config.ru', 'Makefile', 'Gemfile', 'Gemfile.lock']
